"""initial_schema

Revision ID: 7360624bd9ae
Revises: 
Create Date: 2026-04-29 20:49:26.898647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7360624bd9ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('ambulance_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_gps_update', sa.DateTime(), nullable=True),
    sa.Column('home_station_lat', sa.Float(), nullable=True),
    sa.Column('home_station_lng', sa.Float(), nullable=True),
    sa.Column('home_station_name', sa.String(length=100), nullable=True),
    sa.Column('paramedic_name', sa.String(length=100), nullable=True),
    sa.Column('paramedic_phone', sa.String(length=20), nullable=True),
    sa.Column('paramedic_certification', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('last_service_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambulances_current_lat'), ['current_lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulances_current_lng'), ['current_lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulances_registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ambulances_status'), ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lng', sa.Float(), nullable=False),
    sa.Column('location_address', sa.String(length=300), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('gcs_score', sa.Integer(), nullable=True),
    sa.Column('predicted_severity', sa.Integer(), nullable=True),
    sa.Column('severity_confidence', sa.Float(), nullable=True),
    sa.Column('inferred_patient_type', sa.String(length=30), nullable=True),
    sa.Column('is_multi_casualty', sa.Boolean(), nullable=True),
    sa.Column('casualty_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergencies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergencies_location_lat'), ['location_lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergencies_location_lng'), ['location_lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergencies_status'), ['status'], unique=False)

    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('total_beds_general', sa.Integer(), nullable=True),
    sa.Column('available_beds_general', sa.Integer(), nullable=True),
    sa.Column('total_beds_icu', sa.Integer(), nullable=True),
    sa.Column('available_beds_icu', sa.Integer(), nullable=True),
    sa.Column('total_beds_trauma', sa.Integer(), nullable=True),
    sa.Column('available_beds_trauma', sa.Integer(), nullable=True),
    sa.Column('total_beds_pediatric', sa.Integer(), nullable=True),
    sa.Column('available_beds_pediatric', sa.Integer(), nullable=True),
    sa.Column('total_beds_burns', sa.Integer(), nullable=True),
    sa.Column('available_beds_burns', sa.Integer(), nullable=True),
    sa.Column('er_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('is_diversion', sa.Boolean(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_lng'), ['lng'], unique=False)

    op.create_table('traffic_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('zone_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.Float(), nullable=True),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_zone_id'), ['zone_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_on_scene_at', sa.DateTime(), nullable=True),
    sa.Column('departed_scene_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_hospital_at', sa.DateTime(), nullable=True),
    sa.Column('predicted_eta_seconds', sa.Integer(), nullable=True),
    sa.Column('actual_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('hospital_recommendation_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('dispatcher_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergencies.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatches_ambulance_id'), ['ambulance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_dispatched_at'), ['dispatched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_emergency_id'), ['emergency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatches_status'))
        batch_op.drop_index(batch_op.f('ix_dispatches_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_emergency_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_dispatched_at'))
        batch_op.drop_index(batch_op.f('ix_dispatches_ambulance_id'))

    op.drop_table('dispatches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_zone_id'))
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_id'))

    op.drop_table('traffic_snapshots')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_lng'))
        batch_op.drop_index(batch_op.f('ix_hospitals_lat'))
        batch_op.drop_index(batch_op.f('ix_hospitals_id'))

    op.drop_table('hospitals')
    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergencies_status'))
        batch_op.drop_index(batch_op.f('ix_emergencies_location_lng'))
        batch_op.drop_index(batch_op.f('ix_emergencies_location_lat'))
        batch_op.drop_index(batch_op.f('ix_emergencies_id'))
        batch_op.drop_index(batch_op.f('ix_emergencies_created_at'))

    op.drop_table('emergencies')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulances_status'))
        batch_op.drop_index(batch_op.f('ix_ambulances_registration_number'))
        batch_op.drop_index(batch_op.f('ix_ambulances_id'))
        batch_op.drop_index(batch_op.f('ix_ambulances_current_lng'))
        batch_op.drop_index(batch_op.f('ix_ambulances_current_lat'))

    op.drop_table('ambulances')
    # ### end Alembic commands ###
