"""ambulance_assigned_user

Revision ID: 25c647b1d021
Revises: 6a96354fce17
Create Date: 2026-04-29 21:01:05.814844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c647b1d021'
down_revision: Union[str, None] = '6a96354fce17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ambulances_assigned_user_id'),
                              ['assigned_user_id'], unique=True)
        batch_op.create_foreign_key('fk_ambulances_assigned_user_id_users',
                                    'users', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ambulances_assigned_user_id_users',
                                 type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ambulances_assigned_user_id'))
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###
