"""tenants_and_tenant_ids

Revision ID: 906248210afd
Revises: 9cb308c783bb
Create Date: 2026-04-30 15:06:42.326650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906248210afd'
down_revision: Union[str, None] = '9cb308c783bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('city_lat', sa.String(length=20), nullable=True),
    sa.Column('city_lng', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ambulances_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_ambulances_tenant_id_tenants',
                                    'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dispatches_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_dispatches_tenant_id_tenants',
                                    'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emergencies_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_emergencies_tenant_id_tenants',
                                    'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hospitals_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_hospitals_tenant_id_tenants',
                                    'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_users_tenant_id_tenants',
                                    'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hospitals_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_hospitals_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_emergencies_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_emergencies_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dispatches_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dispatches_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ambulances_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ambulances_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
