"""family_link_notes

Revision ID: f0ad4fd43fa3
Revises: 7818e25af901
Create Date: 2026-04-30 13:59:10.099448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ad4fd43fa3'
down_revision: Union[str, None] = '7818e25af901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_link_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_link_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_link_id'], ['family_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_link_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_link_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_link_notes_family_link_id'), ['family_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_link_notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_link_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_link_notes_id'))
        batch_op.drop_index(batch_op.f('ix_family_link_notes_family_link_id'))
        batch_op.drop_index(batch_op.f('ix_family_link_notes_created_at'))

    op.drop_table('family_link_notes')
    # ### end Alembic commands ###
