"""patient_layer

Revision ID: 6a96354fce17
Revises: 7360624bd9ae
Create Date: 2026-04-29 20:53:17.913975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a96354fce17'
down_revision: Union[str, None] = '7360624bd9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('home_lat', sa.String(length=20), nullable=True),
    sa.Column('home_lng', sa.String(length=20), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('family_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('nok_name', sa.String(length=120), nullable=True),
    sa.Column('nok_phone', sa.String(length=20), nullable=True),
    sa.Column('nok_relation', sa.String(length=40), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_links_emergency_id'), ['emergency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_links_token_hash'), ['token_hash'], unique=True)

    op.create_table('hospital_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('emergency_id', sa.Integer(), nullable=False),
    sa.Column('severity_level', sa.Integer(), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('patient_type', sa.String(length=40), nullable=True),
    sa.Column('briefing', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergencies.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_alerts_dispatch_id'), ['dispatch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_alerts_emergency_id'), ['emergency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_alerts_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_alerts_status'), ['status'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_summary', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('hospital_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_hospital_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_alerts_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_alerts_emergency_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_alerts_dispatch_id'))

    op.drop_table('hospital_alerts')
    with op.batch_alter_table('family_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_links_token_hash'))
        batch_op.drop_index(batch_op.f('ix_family_links_id'))
        batch_op.drop_index(batch_op.f('ix_family_links_emergency_id'))

    op.drop_table('family_links')
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_patient_profiles_id'))

    op.drop_table('patient_profiles')
    # ### end Alembic commands ###
