"""user_assigned_hospital

Revision ID: 7891444adb71
Revises: 25c647b1d021
Create Date: 2026-04-29 21:06:59.492829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7891444adb71'
down_revision: Union[str, None] = '25c647b1d021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_hospital_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_assigned_hospital_id'),
                              ['assigned_hospital_id'], unique=False)
        batch_op.create_foreign_key('fk_users_assigned_hospital_id_hospitals',
                                    'hospitals', ['assigned_hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_assigned_hospital_id_hospitals',
                                 type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_assigned_hospital_id'))
        batch_op.drop_column('assigned_hospital_id')

    # ### end Alembic commands ###
