"""notification_subscriptions

Revision ID: 6d678142dcf1
Revises: 7891444adb71
Create Date: 2026-04-29 21:17:42.033476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d678142dcf1'
down_revision: Union[str, None] = '7891444adb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_channel'))

    op.drop_table('notification_subscriptions')
    # ### end Alembic commands ###
