"""patient_telemetry

Revision ID: 7818e25af901
Revises: 6d678142dcf1
Create Date: 2026-04-30 13:52:49.978752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7818e25af901'
down_revision: Union[str, None] = '6d678142dcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('body_temperature_c', sa.Float(), nullable=True),
    sa.Column('glucose_mg_dl', sa.Integer(), nullable=True),
    sa.Column('steps_since_midnight', sa.Integer(), nullable=True),
    sa.Column('fall_detected', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_telemetry_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_telemetry_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_telemetry_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_telemetry_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_telemetry_source'))
        batch_op.drop_index(batch_op.f('ix_patient_telemetry_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_patient_telemetry_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_telemetry_id'))

    op.drop_table('patient_telemetry')
    # ### end Alembic commands ###
