"""mci_incidents_and_victims

Revision ID: fb9c877d7d99
Revises: 906248210afd
Create Date: 2026-04-30 15:13:33.383814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9c877d7d99'
down_revision: Union[str, None] = '906248210afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mci_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lng', sa.Float(), nullable=False),
    sa.Column('location_address', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('estimated_victim_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('declared_by_user_id', sa.Integer(), nullable=True),
    sa.Column('declared_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['declared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mci_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mci_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mci_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mci_incidents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mci_victims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('can_walk', sa.Boolean(), nullable=True),
    sa.Column('breathing', sa.Boolean(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('capillary_refill_seconds', sa.Float(), nullable=True),
    sa.Column('follows_commands', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('raw_assessment', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dispatched_to_dispatch_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispatched_to_dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['mci_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mci_victims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mci_victims_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_mci_victims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mci_victims_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mci_victims_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mci_victims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mci_victims_status'))
        batch_op.drop_index(batch_op.f('ix_mci_victims_incident_id'))
        batch_op.drop_index(batch_op.f('ix_mci_victims_id'))
        batch_op.drop_index(batch_op.f('ix_mci_victims_category'))

    op.drop_table('mci_victims')
    with op.batch_alter_table('mci_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mci_incidents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mci_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_mci_incidents_id'))

    op.drop_table('mci_incidents')
    # ### end Alembic commands ###
